# Generated by Django 4.2.11 on 2024-04-14 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CLOs1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.IntegerField()),
                ('content', models.CharField(max_length=255)),
                ('PLO', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CLOs2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.IntegerField()),
                ('a', models.CharField(blank=True, max_length=1)),
                ('b', models.CharField(blank=True, max_length=1)),
                ('c', models.CharField(blank=True, max_length=1)),
                ('d', models.CharField(blank=True, max_length=1)),
                ('e', models.CharField(blank=True, max_length=1)),
                ('f', models.CharField(blank=True, max_length=1)),
                ('g', models.CharField(blank=True, max_length=1)),
                ('h', models.CharField(blank=True, max_length=1)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CLOs3',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.IntegerField()),
                ('exam', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=255)),
                ('point', models.CharField(max_length=255)),
                ('criteria', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.IntegerField()),
                ('content', models.TextField()),
                ('number_session', models.CharField(max_length=255)),
                ('CLOs', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=255)),
                ('self_study', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id_curriculum', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('number_credit', models.CharField(max_length=255)),
                ('document', models.TextField()),
                ('target', models.TextField()),
                ('description', models.TextField()),
                ('subject_similar', models.IntegerField()),
                ('time_update', models.CharField(max_length=255)),
                ('CLOs1', models.ManyToManyField(to='site1.clos1')),
                ('CLOs2', models.ManyToManyField(to='site1.clos2')),
                ('CLOs3', models.ManyToManyField(to='site1.clos3')),
                ('content', models.ManyToManyField(to='site1.content')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id_curriculum', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectPre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('role', models.IntegerField()),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('gmail', models.EmailField(max_length=254)),
                ('Curriculum', models.ManyToManyField(related_name='Curriculum_users', to='site1.curriculum')),
                ('courses', models.ManyToManyField(related_name='Course_user', to='site1.course')),
            ],
            options={
                'ordering': ['first_name'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumCourse',
            fields=[
                ('id_curriculumCourse', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('mandatory', models.BooleanField()),
                ('is_confirm', models.BooleanField()),
                ('semester', models.IntegerField()),
                ('id_course', models.ManyToManyField(to='site1.course')),
                ('teacher', models.ManyToManyField(to='site1.user')),
            ],
        ),
        migrations.AddField(
            model_name='curriculum',
            name='curriculum_course',
            field=models.ManyToManyField(to='site1.curriculumcourse'),
        ),
        migrations.AddField(
            model_name='course',
            name='head_department',
            field=models.ManyToManyField(related_name='courses_as_head_department', to='site1.user'),
        ),
        migrations.AddField(
            model_name='course',
            name='primary_teacher',
            field=models.ManyToManyField(related_name='courses_as_primary_teacher', to='site1.user'),
        ),
        migrations.AddField(
            model_name='course',
            name='subject_pre',
            field=models.ManyToManyField(to='site1.subjectpre'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ManyToManyField(related_name='courses_as_teacher', to='site1.user'),
        ),
        migrations.AddField(
            model_name='course',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculums', to='site1.user'),
        ),
    ]
