# Generated by Django 4.2.11 on 2024-04-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='user',
            field=models.ManyToManyField(to='site1.user'),
        ),
    ]
