# Generated by Django 4.2.11 on 2024-04-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0002_curriculum_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clos1',
            name='PLO',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='clos1',
            name='content',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='clos1',
            name='order',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='CLOs1',
            field=models.ManyToManyField(blank=True, to='site1.clos1'),
        ),
        migrations.AlterField(
            model_name='course',
            name='CLOs2',
            field=models.ManyToManyField(blank=True, to='site1.clos2'),
        ),
        migrations.AlterField(
            model_name='course',
            name='CLOs3',
            field=models.ManyToManyField(blank=True, to='site1.clos3'),
        ),
        migrations.AlterField(
            model_name='course',
            name='content',
            field=models.ManyToManyField(blank=True, to='site1.content'),
        ),
        migrations.AlterField(
            model_name='course',
            name='head_department',
            field=models.ManyToManyField(blank=True, related_name='courses_as_head_department', to='site1.user'),
        ),
        migrations.AlterField(
            model_name='course',
            name='primary_teacher',
            field=models.ManyToManyField(blank=True, related_name='courses_as_primary_teacher', to='site1.user'),
        ),
        migrations.AlterField(
            model_name='course',
            name='subject_pre',
            field=models.ManyToManyField(blank=True, to='site1.subjectpre'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ManyToManyField(blank=True, related_name='courses_as_teacher', to='site1.user'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='curriculum_course',
            field=models.ManyToManyField(blank=True, to='site1.curriculumcourse'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='user',
            field=models.ManyToManyField(blank=True, to='site1.user'),
        ),
        migrations.AlterField(
            model_name='curriculumcourse',
            name='id_course',
            field=models.ManyToManyField(blank=True, to='site1.course'),
        ),
        migrations.AlterField(
            model_name='curriculumcourse',
            name='teacher',
            field=models.ManyToManyField(blank=True, to='site1.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Curriculum',
            field=models.ManyToManyField(blank=True, related_name='Curriculum_users', to='site1.curriculum'),
        ),
        migrations.AlterField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='Course_user', to='site1.course'),
        ),
    ]
