# Generated by Django 4.2.11 on 2024-04-14 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0003_alter_clos1_plo_alter_clos1_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculum',
            name='user',
        ),
    ]
