# Generated by Django 4.2.11 on 2024-04-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0004_remove_curriculum_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curriculum',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='curriculumcourse',
            options={'ordering': ['id_curriculumCourse']},
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='curriculum_course',
            field=models.ManyToManyField(blank=True, related_name='curriculum_course_ids', to='site1.curriculumcourse'),
        ),
        migrations.AlterField(
            model_name='curriculumcourse',
            name='is_confirm',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='curriculumcourse',
            name='mandatory',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='curriculumcourse',
            name='semester',
            field=models.IntegerField(default=1),
        ),
    ]
