# Generated by Django 4.2.11 on 2024-04-15 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0005_alter_curriculum_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='user',
        ),
    ]
