# Generated by Django 4.2.11 on 2024-04-16 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0006_remove_course_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='id_curriculum',
            new_name='id_course_main',
        ),
    ]
