# Generated by Django 4.2.11 on 2024-04-16 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0007_rename_id_curriculum_course_id_course_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clos3',
            name='criteria',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='clos3',
            name='exam',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='clos3',
            name='method',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='clos3',
            name='order',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='clos3',
            name='point',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='gmail',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
