# Generated by Django 4.2.11 on 2024-04-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0008_alter_clos3_criteria_alter_clos3_exam_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(default='chua co du lieu'),
        ),
        migrations.AlterField(
            model_name='course',
            name='document',
            field=models.TextField(default='chua co du lieu'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(default='chau co du lieu', max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='number_credit',
            field=models.CharField(default='chua co du lieu', max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='subject_similar',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='target',
            field=models.TextField(default='chua co du lieu'),
        ),
        migrations.AlterField(
            model_name='course',
            name='time_update',
            field=models.CharField(default='chua co du lieu', max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(default='chua co du lieu', max_length=255),
        ),
    ]
